### ISSUE TITLE
On reply, always captured frame is different from current one

### ISSUE THREAD

**Issue by mostafa-hassan** [csudanthi/AutoGUI#1]
for some reason, the captured frame get corrupted and need to be re-read from hard disk with every check ( not only once as currently implemented)

my fix was to read it every time from the hard disk frame buffer file before comparing it with current frame. Specifically, in file client.cpp, function "HandleReplayerInput":

there are two calls for TryMatchFrame(), before each one of them you need to call GetTargetFrame()

so, basically, the code inside the function looks like this now:
void HandleReplayerInput(SocketSet *c_sockset)
{
    uint32_t n, i;
    fd_set rfds;
    struct timeval tv;
    static AU_BOOL WaitForFrame = False;
    AU_BOOL match;
    ofstream TmpPixelData;
    char pathFrameCheck[1024];
    memset(pathFrameCheck, 0, sizeof(pathFrameCheck));

```
if (WaitForFrame) {
    FD_ZERO(&rfds);
    FD_SET(c_sockset->SocketToServer, &rfds);
    tv.tv_sec = 10;
    tv.tv_usec = 0;
    n = c_sockset->SocketToServer + 1;
    i = select(n, &rfds, NULL, NULL, &tv);
    switch (i) {
      case 0:
        // timeout
        GetThreshold();
        GetTargetFrame();
        match = TryMatchFrame();
        if (match) {
            WaitForFrame = False;
            FrameCnt++;
        } else {
            cout << "[Replaying HandleReplayerInput] select"
                 << " timeout(10s). FrameCnt = " << dec
                 << (int)FrameCnt << endl;

            cout << "Write CurPixelData and CapPixelData into .bmp"
                 << " file for check" << endl;
            INIT_BMP(TmpBMPHead);
            sprintf(pathFrameCheck, "framein/fb%06u_raw_Current.bmp",
                    FrameCnt);
            TmpPixelData.open(pathFrameCheck);
            pthread_mutex_lock(&mutex);
            TmpPixelData.write((char *)&TmpBMPHead, sizeof(TmpBMPHead));
            TmpPixelData.write((char *)&CurPixelData[0],
                sizeof(CurPixelData));
            pthread_mutex_unlock(&mutex);
            TmpPixelData.close();
            sprintf(pathFrameCheck, "framein/fb%06u_raw_Capture.bmp",
                    FrameCnt);
            TmpPixelData.open(pathFrameCheck);
            TmpPixelData.write((char *)&TmpBMPHead, sizeof(TmpBMPHead));
            TmpPixelData.write((char *)&CapPixelData[0],
                sizeof(CapPixelData));
            TmpPixelData.close();
        }
        break;
      case 1:
        // socket can be read now
    GetThreshold();
        GetTargetFrame();
        match = TryMatchFrame();
        if (match) {
            WaitForFrame = False;
            FrameCnt++;
        }
        pthread_mutex_lock(&mutex);
        log << "a new pixel data received, TryMatchFrame again."
            << "  WaitForFrame = " << dec << (int)WaitForFrame << endl;

        pthread_mutex_unlock(&mutex);
        break;
      default:
        error(False, "ERROR: [HandleReplayerInput] select"
                     " c_sockset->SocketToServer");
    }
} else {
    WaitForFrame = SendReplayerInput(c_sockset);
}
```

}

**Comment by PerthCharles** [comment]
> >  for some reason, the captured frame get corrupted and need to be re-read from hard disk with every check 
> > <<  can you give more details about how and in which case the captured frame will be corrupted ?  

I believe that your solution can fix the problem you encountered，but maybe a better solution is find out the reason for corrupted frame. :)

**Comment by mostafa-hassan** [comment]
Here is the scenario of what happened.
1- I started to record, successfully finished my 5 steps test case and all the frames corresponding to the steps are recorded in a correct way.
2- when I come to reply, the first frame(number 0) is matched at once and the first step of my test case is replayed with no problems.
3- Then, for some reason, the VNC client stays like that for 10 seconds while the actual machine progressed to the next step. This indicates that AutoGUI is not forwarding what it receives from the VNC server to the VNC client. From the code I can see that you timeout after 10 seconds and this is the time it takes AutoGUI to come back to correct stream forwarding. This of course causes the matching process to timeout after 10 seconds and dumps (fb000001_raw_Capture.bmp) and (fb000001_raw_Current.bmp). 
4- But, finally when AutoGUI syncs,  frame (number 1) is correctly matched and the step is replayed.
5- at frame #2, while trying to match the captured vs current, the captured correclty similar to fb000002_raw.bmp till the first timeout (10 seconds). Then it becomes like two frames overwritten on each other with one shifted about half the way up. so, starting from this point it never matches the current frame and the replay got stuck at this point. 

I bieleve that it is related to the out of sync I mentioned at point number 3 above. I can say that while replaying, AutoGUI is becoming out of sync and does not forwardwhat it receives from the VNC server. The VNC client hangs for like 10 seconds while the actual machine moves forward.

**Comment by PerthCharles** [comment]
Thank you for your patient descriptions and your PR, which have been merged.

In my understanding, the AutoGUI will forward what it receives from the VNC server to VNC client, otherwise you cannot see any changes in VNC client when replaying. So, I am still confused about why the AutoGUI becomes out of sync. 

Doesn't this happened at every time and in every cases ?
Have you check out the threshold for your captured frames ? is that too small ?
and have you notice that there is 500ms delay between CaptureFrame() and WriteThreshold(). You need to consider this time gap request when recording your actions.

**Comment by mostafa-hassan** [comment]
" AutoGUI will forward what it receives from the VNC server to VNC client, otherwise you cannot see any changes in VNC client when replaying" 
This happens ...but after around 10 seconds of the first action being replayed .... as I said, the first frame matches, so first action is replayed, then the emulator screen updates reflecting the action BUT the VNC still shows the old screen for about 10 sec during which the autogui keeps trying to match the second frame ..... finally vnc client updates !!! ....only at that moment, the second frame matches and the second step is replayed ...... on the third step, the frame tries to match then get corrupted and the replay never proceeds.
I can video what happens and send it to you. A better fix, rather than reading from disk, would be to use another variable for captured frame buffer than CapPixelData to read once from disk ...that way we are sure no other code in autogui will overwrite it...may be it is being overwritten somehow.

the threshold is pretty high .97 ..97% match ...but will comparing, because of the corrupted frame, it is around 81% 

"You need to consider this time gap request when recording your actions." I was cautious to the extent that I waited for 10 seconds between every step and the next while recording !
